# The URL the site will be built for
base_url = "https://iogamaster.github.io"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "papermod"

taxonomies = [
    { name = "tags", feed = true }
]

[markdown]
highlight_code = true

[extra]

[extra.papermod]
title = "IogaMaster"
default_theme = "auto"
theme = "dark"
language_direction = "auto"
keywords = ["iogamaster", "nix", "nixos", "rust", "zig"]
show_theme_toggle = true
show_scroll_to_top = true
show_code_copy_buttons = true
show_reading_time = true
show_word_count = false
show_post_nav_links = true
show_post_meta = true
default_toc_open = false
show_post_edit_button = false
edit_post_url = "https://github.com/IogaMaster/iogamaster.github.io/tree/main"
date_format = "%Y-%m-%d"
navigation = [
    { url = "$BASE_URL/archive", title = "Archive" },
    { url = "$BASE_URL/tags", title = "Tags" },
    { url = "https://getzola.com/", title = "Zola", is_external = true }
]

home_title = "IogaMaster"
home_content = "I contribute to open source sometimes. <br> | Linux | Nix | NixOS | Rust | Zig |"
social_icons = [
    { url = "https://github.com/IogaMaster", title = "GitHub", icon = "github" },
    { url = "https://youtube.com/IogaMaster", title = "YouTube", icon = "youtube" },
    { url = "https://ko-fi.com/IogaMaster", title = "Ko-Fi", icon = "ko-fi" },
    { url = "$BASE_URL/atom.xml", title = "RSS", icon = "rss" },
]
